import {
  XIcon,
  Loader2Icon,
  MenuIcon,
  PaletteIcon,
  HomeIcon,
  SettingsIcon,
  SwatchBookIcon,
  LogOutIcon,
  SendHorizontalIcon,
  DicesIcon,
  MoonIcon,
  SunIcon,
  ArrowRightIcon,
  HistoryIcon,
  HeartIcon,
  CopyIcon,
} from "lucide-react";

export const Icons = {
  close: XIcon,
  loader: Loader2Icon,
  menu: MenuIcon,
  home: HomeIcon,
  playground: SwatchBookIcon,
  settings: SettingsIcon,
  logout: LogOutIcon,
  palette: PaletteIcon,
  sendHorizontal: SendHorizontalIcon,
  dices: DicesIcon,
  moon: MoonIcon,
  sun: SunIcon,
  arrowRight: ArrowRightIcon,
  history: HistoryIcon,
  heart: HeartIcon,
  copy: CopyIcon,
} as const;
